Name: Anmol Shrestha

Section: L6CG19

Worksheet-0

# TO DO TASK

#4.1.Exercie on Functions

**Task - 1:**

Create a Python program that converts between different units of measurement.

*  The program should:

    1.Prompt the user to choose the type of conversion (e.g., length, weight, volume).

    2.Ask the user to input the value to be converted.

    3.Perform the conversion and display the result.

    4.Handle potential errors, such as invalid input or unsupported conversion types.

*  Requirements:

    1.Functions: Define at least one function to perform the conversion.

    2.Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

    3.User Input: Prompt the user to select the conversion type and input the value.

    4.Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.



*   Conversion Options:

    1.Length:

    * Convert meters (m) to feet (ft).
    * Convert feet (ft) to meters (m).

    2.Weight:
    * Convert kilograms (kg) to pounds (lbs).
    * Convert pounds (lbs) to kilograms (kg).

    3.Volume:
    * Convert liters (L) to gallons (gal).
    * Convert gallons (gal) to liters (L).

In [1]:
def get_choice():
    """
    Prompts the user to choose a conversion type and returns the corresponding conversion details.
    """

    conversion_options = {
       "1": ("meters_to_feet", "Length: Meters (m) to Feet (ft)", "m", "ft"),
        "2": ("feet_to_meters", "Length: Feet (ft) to Meters (m)", "ft", "m"),
        "3": ("kilograms_to_pounds", "Weight: Kilograms (kg) to Pounds (lbs)", "kg", "lbs"),
        "4": ("pounds_to_kilograms", "Weight: Pounds (lbs) to Kilograms (kg)", "lbs", "kg"),
        "5": ("liters_to_gallons", "Volume: Liters (L) to Gallons (gal)", "L", "gal"),
        "6": ("gallons_to_liters", "Volume: Gallons (gal) to Liters (L)", "gal", "L")
    }

    print("\nWelcome to the Unit Converter ")
    print("Choose a conversion option from the list below:")
    for key, value in conversion_options.items():
        print(f"{key}. {value[1]}")

    choice = input("Enter the number of the conversion you want: ").strip()
    return conversion_options.get(choice, None)

def perform_conversion(value, conv_type):
    """
    Performs the unit conversion based on the selected conversion type.

    Parameters:
    value -> float: The value that must be converted.
    conv_type -> str: The choice of conversion type
    """
    conv_functions = {
        "meters_to_feet": lambda v: v * 3.281,
        "feet_to_meters": lambda v: v / 3.281,
        "kilograms_to_pounds": lambda v: v * 2.20462,
        "pounds_to_kilograms": lambda v: v * 0.453592,
        "liters_to_gallons": lambda v: v * 0.264172,
        "gallons_to_liters": lambda v: v * 3.78541
    }

    return conv_functions.get(conv_type, lambda v: None)(value)

def main():
    while True:
        conversion_choice = get_choice()

        if not conversion_choice:
            print("\nInvalid choice. Please select a valid option for the list.\n")
            continue

        conv_type, description, from_unit, to_unit = conversion_choice
        print(f"You have selected:\n{description}")

        try:
            value = float(input(f"\nEnter the value in {from_unit}: "))
            converted_value = perform_conversion(value, conv_type)

            if converted_value is not None:
                print(f"Result: {value} {from_unit} is equal to {converted_value:.4f} {to_unit}")
            else:
                print("Conversion error. Please try again.")

        except ValueError:
            print("Invalid input. Please enter a valid number.")

        another = input("\nWould you like to perform another conversion? (yes/no): ").strip().lower()
        if another != "yes":
            print("End of program! Thank you for using the Unit Converter!")
            break

if __name__ == "__main__":
    main()


Welcome to the Unit Converter 
Choose a conversion option from the list below:
1. Length: Meters (m) to Feet (ft)
2. Length: Feet (ft) to Meters (m)
3. Weight: Kilograms (kg) to Pounds (lbs)
4. Weight: Pounds (lbs) to Kilograms (kg)
5. Volume: Liters (L) to Gallons (gal)
6. Volume: Gallons (gal) to Liters (L)
Enter the number of the conversion you want: 5
You have selected:
Volume: Liters (L) to Gallons (gal)

Enter the value in L: 2
Result: 2.0 L is equal to 0.5283 gal

Would you like to perform another conversion? (yes/no): no
End of program! Thank you for using the Unit Converter!


**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.

* The program should:

  1.Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers)

  2.Ask the user to input a list of numbers (separated by spaces).

  3.Perform the selected operation and display the result.

  4.Handle potential errors, such as invalid input or empty lists.

* Requirements:

  1.Functions: Define at least one function for each operation (sum, average, maximum, minimum).

  2.Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).

  3.User Input: Prompt the user to select the operation and input the list of numbers.

  4.Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value.

In [3]:
def find_sum(nums):
  return sum(nums)

def find_average(nums):
  return sum(nums)/len(nums)

def find_max(nums):
  return max(nums)

def find_min(nums):
  return min(nums)

def get_numbers_from_user():
  """
  Function to get a list of numbers from the user input.
  """
  while True:
    try:
      numbers = list(map(float,input("Enter numbers separated by spaces: ").split()))
      if not numbers:
        print("Error: The list cannot be empty. Please enter at leeast one number")
        continue
      return numbers
    except ValueError:
      print("Error: Invalid input. Please enter numbers separated by spaces.")


def main():
  operations = {
      "1": ("Sum", find_sum),
      "2": ("Average", find_average),
      "3": ("Maximum", find_max),
      "4": ("Minimum", find_min)
  }
  while True:
    print("Welcome to the Program!")
    print("Choose a mathematical operations: ")
    for key,(name,_) in operations.items():
      print(f"{key}. {name}")

    choice = input("Enter the numbers of the operation you want to perform:").strip()

    if choice not in operations:
      print("Invalid choice. Please select a valid option.\n")
      continue

    operation_name, operation_func = operations[choice]
    print(f"You have selected: {operation_name}")

    num = get_numbers_from_user()
    result = operation_func(num)

    if result is not None:
      print(f"Result:{result}")
    else:
      print("Error")

    again = input("\nDo you want to perform another operation? (yes/no): ").strip().lower()
    if again != "yes":
      print("End of program! Thank you for using the Program!")
      break

if __name__ == "__main__":
  main()


Welcome to the Program!
Choose a mathematical operations: 
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the numbers of the operation you want to perform:4
You have selected: Minimum
Enter numbers separated by spaces: 2
Result:2.0

Do you want to perform another operation? (yes/no): no
End of program! Thank you for using the Program!


#4.2.Exercise on List Manipulation:

**Task - 1:**

Create a Python program that converts between different units of measurement.

*  The program should:

    1.Prompt the user to choose the type of conversion (e.g., length, weight, volume).

    2.Ask the user to input the value to be converted.

    3.Perform the conversion and display the result.

    4.Handle potential errors, such as invalid input or unsupported conversion types.

*  Requirements:

    1.Functions: Define at least one function to perform the conversion.

    2.Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

    3.User Input: Prompt the user to select the conversion type and input the value.

    4.Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.



*   Conversion Options:

    1.Length:

    * Convert meters (m) to feet (ft).
    * Convert feet (ft) to meters (m).

    2.Weight:
    * Convert kilograms (kg) to pounds (lbs).
    * Convert pounds (lbs) to kilograms (kg).

    3.Volume:
    * Convert liters (L) to gallons (gal).
    * Convert gallons (gal) to liters (L).

In [4]:
def get_choice():
    """
    Prompts the user to choose a conversion type and returns the corresponding conversion details.
    """

    conversion_options = {
       "1": ("meters_to_feet", "Length: Meters (m) to Feet (ft)", "m", "ft"),
        "2": ("feet_to_meters", "Length: Feet (ft) to Meters (m)", "ft", "m"),
        "3": ("kilograms_to_pounds", "Weight: Kilograms (kg) to Pounds (lbs)", "kg", "lbs"),
        "4": ("pounds_to_kilograms", "Weight: Pounds (lbs) to Kilograms (kg)", "lbs", "kg"),
        "5": ("liters_to_gallons", "Volume: Liters (L) to Gallons (gal)", "L", "gal"),
        "6": ("gallons_to_liters", "Volume: Gallons (gal) to Liters (L)", "gal", "L")
    }

    print("\nWelcome to the Unit Converter ")
    print("Choose a conversion option from the list below:")
    for key, value in conversion_options.items():
        print(f"{key}. {value[1]}")

    choice = input("Enter the number of the conversion you want: ").strip()
    return conversion_options.get(choice, None)

def perform_conversion(value, conv_type):
    """
    Performs the unit conversion based on the selected conversion type.

    Parameters:
    value -> float: The value that must be converted.
    conv_type -> str: The choice of conversion type
    """
    conv_functions = {
        "meters_to_feet": lambda v: v * 3.281,
        "feet_to_meters": lambda v: v / 3.281,
        "kilograms_to_pounds": lambda v: v * 2.20462,
        "pounds_to_kilograms": lambda v: v * 0.453592,
        "liters_to_gallons": lambda v: v * 0.264172,
        "gallons_to_liters": lambda v: v * 3.78541
    }

    return conv_functions.get(conv_type, lambda v: None)(value)

def main():
    while True:
        conversion_choice = get_choice()

        if not conversion_choice:
            print("\nInvalid choice. Please select a valid option for the list.\n")
            continue

        conv_type, description, from_unit, to_unit = conversion_choice
        print(f"You have selected:\n{description}")

        try:
            value = float(input(f"\nEnter the value in {from_unit}: "))
            converted_value = perform_conversion(value, conv_type)

            if converted_value is not None:
                print(f"Result: {value} {from_unit} is equal to {converted_value:.4f} {to_unit}")
            else:
                print("Conversion error. Please try again.")

        except ValueError:
            print("Invalid input. Please enter a valid number.")

        another = input("\nWould you like to perform another conversion? (yes/no): ").strip().lower()
        if another != "yes":
            print("End of program! Thank you for using the Unit Converter!")
            break

if __name__ == "__main__":
    main()


Welcome to the Unit Converter 
Choose a conversion option from the list below:
1. Length: Meters (m) to Feet (ft)
2. Length: Feet (ft) to Meters (m)
3. Weight: Kilograms (kg) to Pounds (lbs)
4. Weight: Pounds (lbs) to Kilograms (kg)
5. Volume: Liters (L) to Gallons (gal)
6. Volume: Gallons (gal) to Liters (L)
Enter the number of the conversion you want: 3
You have selected:
Weight: Kilograms (kg) to Pounds (lbs)

Enter the value in kg: 25
Result: 25.0 kg is equal to 55.1155 lbs

Would you like to perform another conversion? (yes/no): no
End of program! Thank you for using the Unit Converter!


**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.

* The program should:

  1.Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers)

  2.Ask the user to input a list of numbers (separated by spaces).

  3.Perform the selected operation and display the result.

  4.Handle potential errors, such as invalid input or empty lists.

* Requirements:

  1.Functions: Define at least one function for each operation (sum, average, maximum, minimum).

  2.Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).

  3.User Input: Prompt the user to select the operation and input the list of numbers.

  4.Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value.

In [5]:
def find_sum(nums):
  return sum(nums)

def find_average(nums):
  return sum(nums)/len(nums)

def find_max(nums):
  return max(nums)

def find_min(nums):
  return min(nums)

def get_numbers_from_user():
  """
  Function to get a list of numbers from the user input.
  """
  while True:
    try:
      numbers = list(map(float,input("Enter numbers separated by spaces: ").split()))
      if not numbers:
        print("Error: The list cannot be empty. Please enter at leeast one number")
        continue
      return numbers
    except ValueError:
      print("Error: Invalid input. Please enter numbers separated by spaces.")


def main():
  operations = {
      "1": ("Sum", find_sum),
      "2": ("Average", find_average),
      "3": ("Maximum", find_max),
      "4": ("Minimum", find_min)
  }
  while True:
    print("Welcome to the Program!")
    print("Choose a mathematical operations: ")
    for key,(name,_) in operations.items():
      print(f"{key}. {name}")

    choice = input("Enter the numbers of the operation you want to perform:").strip()

    if choice not in operations:
      print("Invalid choice. Please select a valid option.\n")
      continue

    operation_name, operation_func = operations[choice]
    print(f"You have selected: {operation_name}")

    num = get_numbers_from_user()
    result = operation_func(num)

    if result is not None:
      print(f"Result:{result}")
    else:
      print("Error")

    again = input("\nDo you want to perform another operation? (yes/no): ").strip().lower()
    if again != "yes":
      print("End of program! Thank you for using the Program!")
      break

if __name__ == "__main__":
  main()


Welcome to the Program!
Choose a mathematical operations: 
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the numbers of the operation you want to perform:4
You have selected: Minimum
Enter numbers separated by spaces: 2
Result:2.0

Do you want to perform another operation? (yes/no): no
End of program! Thank you for using the Program!


#4.2.Exercise on List Manipulation:

1. Extract Every Other Element:

  Write a Python function that extracts every other element from a list, starting from the first element.

* Requirements:

  – Define a function extract every other(lst) that takes a list lst as input and returns a
  new list containing every other element from the original list.

  – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [6]:
def extract(lst):
  """
    Extracts every other element from the input list, starting from the first element.

  """
  return lst[::2]

input_list =[1,2,3,4,5,6,7,8,9]
output_list = extract(input_list)
print("The original list:", input_list)
print("The new list with every other element: ", output_list)

The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9]
The new list with every other element:  [1, 3, 5, 7, 9]


2. Slice a Sublist:

  Write a Python function that returns a sublist from a given list, starting from a specified index and
  ending at another specified index.

* Requirements:

  – Define a function get sublist(lst, start, end) that takes a list lst, a starting index
  start, and an ending index end as input and returns the sublist from start to end (inclusive).

  – Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
  be [3, 4, 5].

In [7]:
def get_sublist(lst, start, end):
  """
    Returns a sublist from a given list, starting from a specified index and ending at another specified index.
  """

  return lst[start:end+1]

input_list = [1, 2, 3, 4, 5, 6, 7, 8]
start = 2
end = 6
result = get_sublist(input_list, start, end)
print("The original list:", input_list)
print("The sublist from specified start to end is: ", result)

The original list: [1, 2, 3, 4, 5, 6, 7, 8]
The sublist from specified start to end is:  [3, 4, 5, 6, 7]


3. Reverse a List Using Slicing:

  Write a Python function that reverses a list using slicing.

* Requirements:

  – Define a function reverse list(lst) that takes a list lst and returns a reversed list using
  slicing.

  – Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [8]:
def reverse_list(lst):
  """
    Reverses the given list and returns the reversed list.
  """
  return lst[::-1]

input_list = [1, 2, 3, 4, 5, 6, 7, 8]
result = reverse_list(input_list)
print("The original list:", input_list)
print("The reversed list is: ", result)

The original list: [1, 2, 3, 4, 5, 6, 7, 8]
The reversed list is:  [8, 7, 6, 5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

  Write a Python function that removes the first and last elements of a list and returns the resulting
  sublist.

* Requirements:

  – Define a function remove first last(lst) that takes a list lst and returns a sublist without
  the first and last elements using slicing.

  – Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [9]:
def remove_first_last(lst):
  """
   Removes the first and last elements of the list.
  """
  return lst[1:-1]

input_listlist = [1, 2, 3, 4, 5, 6, 7, 8]
result = remove_first_last(input_list)
print("The original list:", input_list)
print("The sublist without first and last elements is: ", result)

The original list: [1, 2, 3, 4, 5, 6, 7, 8]
The sublist without first and last elements is:  [2, 3, 4, 5, 6, 7]


5. Get the First n Elements:

  Write a Python function that extracts the first n elements from a list.
* Requirements:

  – Define a function get first n(lst, n) that takes a list lst and an integer n as input and
  returns the first n elements of the list using slicing.

  – Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [10]:
def get_first_n(lst, n):
  """
    Returning the first 'n' elements of the list.
  """
  return lst[:n]

input_list = [1, 2, 3, 4, 5, 6, 7, 8]
n = 6
result = get_first_n(input_list, n)
print("The original list:", input_list)
print("The first", n, "elements of the list are: ", result)

The original list: [1, 2, 3, 4, 5, 6, 7, 8]
The first 6 elements of the list are:  [1, 2, 3, 4, 5, 6]


6. Extract Elements from the End:

  Write a Python function that extracts the last n elements of a list using slicing.

* Requirements:

  – Define a function get last n(lst, n) that takes a list lst and an integer n as input and
  returns the last n elements of the list.

  – Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [11]:
def get_last_n(lst, n):
  """
    Returning the last 'n' elements of the list.
  """
  return lst[-n:]

input_listst = [1, 2, 3, 4, 5, 6, 7, 8]
n = 6
result = get_last_n(input_list, n)
print("The original list:", input_list)
print("The last", n, "elements of the list are: ", result)

The original list: [1, 2, 3, 4, 5, 6, 7, 8]
The last 6 elements of the list are:  [3, 4, 5, 6, 7, 8]


7. Extract Elements in Reverse Order:

  Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
  element and skipping one element in between.

* Requirements:

  – Define a function reverse skip(lst) that takes a list lst and returns a new list containing
  every second element starting from the second-to-last, moving backward.

  – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [12]:
def reverse_skip(lst):
  """
    Slices the list from the second-to-last element and skips every other element in reverse order.
  """
  return lst[-2::-2]

input_list = [1, 2, 3, 4, 5, 6, 7, 8]
result = reverse_skip(input_list)
print("The original list:", input_list)
print("Every other element in reverse order: ",result)

The original list: [1, 2, 3, 4, 5, 6, 7, 8]
Every other element in reverse order:  [7, 5, 3, 1]


#4.3.Exercise on Nested List:

1. Flatten a Nested List:

  Write a Python function that takes a nested list and flattens it into a single list, where all the elements
  are in a single dimension.

* Requirements:

  – Define a function flatten(lst) that takes a nested list lst and returns a flattened version
  of the list.

  – Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [13]:
def flatten(lst):
  """
    Flattens a nested list into a single list.
  """
  flattened_list = []
  for sublist in lst:
    for item in sublist:
      flattened_list.append(item)
  return flattened_list

list = [1, 2], [3, 4], [5, 6], [7, 8]
print("The original list:", list)
flattened_list = flatten(list)
print("The flattened list:", flattened_list)

The original list: ([1, 2], [3, 4], [5, 6], [7, 8])
The flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


2. Accessing Nested List Elements:

  Write a Python function that extracts a specific element from a nested list given its indices.

* Requirements:

  – Define a function access nested element(lst, indices) that takes a nested list lst and
  a list of indices indices, and returns the element at that position.

  – Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
  2], the output should be 6.

In [14]:
def access_nested_element(lst,indices):
  """
  Accessing the element in the nested list using the provided indices.
  """
  target_value = lst[indices[0]][indices[1]]
  return target_value

input_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(input_list, indices)
print("The original list:", input_list)
print("The element at the specified indices is: ", result)

The original list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
The element at the specified indices is:  6


3. Sum of All Elements in a Nested List:

  Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

* Requirements:

  – Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
  the elements.
  
  – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [20]:
def sum_nested(lst):
    """
    Calculates the sum of all elements in a nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

input_list = [[1, 2, 3], [4, 5, [6, 7], 8], [9, 10, 11]]
print("The original list:", input_list)
result = sum_nested(input_list)
print("Sum of all elements in the nested list:", result)


The original list: [[1, 2, 3], [4, 5, [6, 7], 8], [9, 10, 11]]
Sum of all elements in the nested list: 66


4. Remove Specific Element from a Nested List:

  Write a Python function that removes all occurrences of a specific element from a nested list.
* Requirements:

  – Define a function remove element(lst, elem) that removes elem from lst and returns the
  modified list.
  
  – Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
  be [[1], [3], [4, 5]].

In [21]:
def remove_element(lst, elem):
  """
  Removes all occurrences of a specified element from a nested list.
  """
  for sublist in lst:
    while elem in sublist:
      sublist.remove(elem)
  return lst

input_list = [[1, 2, 3, 4], [4, 5, [6, 7], 8], [9, 10, 11]]
elem = 4
print("The original list:", input_list)
result = remove_element(input_list, elem)
print("The modified list after removal of the element is: ", result)

The original list: [[1, 2, 3, 4], [4, 5, [6, 7], 8], [9, 10, 11]]
The modified list after removal of the element is:  [[1, 2, 3], [5, [6, 7], 8], [9, 10, 11]]


5. Find the Maximum Element in a Nested List:

  Write a Python function that finds the maximum element in a nested list (regardless of depth).

* Requirements:

  – Define a function find max(lst) that takes a nested list lst and returns the maximum
  element.

  – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [22]:
def find_max(lst):
    """
    Finding the maximum element in a nested list.
    """
    max_element = float('-inf')  # Initialize max_element to the lowest possible value

    for item in lst:
        if isinstance(item, list):
            max_element = max(max_element, find_max(item))
        else:
            max_element = max(max_element, item)
    return max_element

input_list = [[1, 2, 3, 4], [4, 5, [6, 7], 8], [9, 10, 11]]
print("The original list:", input_list)
result = find_max(input_list)
print("The maximum element in the nested list:", result)


The original list: [[1, 2, 3, 4], [4, 5, [6, 7], 8], [9, 10, 11]]
The maximum element in the nested list: 11


6. Count Occurrences of an Element in a Nested List:

  Write a Python function that counts how many times a specific element appears in a nested list.

* Requirements:

  – Define a function count occurrences(lst, elem) that counts the occurrences of elem in
  the nested list lst.
  
  – Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
  be 3.

In [23]:
def count_occurrences(lst, elem):
    """
    Counting how many times a specific element appears in a nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

input_list = [[1, 2, 4], [4, 5, [6, 4], 8], [9, 4, 10]]
element = 4
print("The original list:", input_list)
result = count_occurrences(input_list, element)
print(f"The element {element} appears {result} times in the nested list.")

The original list: [[1, 2, 4], [4, 5, [6, 4], 8], [9, 4, 10]]
The element 4 appears 4 times in the nested list.


7. Flatten a List of Lists of Lists:

  Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

* Requirements:

  – Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
  flattened list.
  
  – Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
  [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.
    """
    flattened_list = []
    for item in lst:
        if isinstance(item, list):
            flattened_list.extend(deep_flatten(item))
        else:
            flattened_list.append(item)
    return flattened_list

input_list = [[1, 2, 3], [4, 5, [6, 7]], [8, 9, 10]]
print("The original list:", input_list)
result = deep_flatten(input_list)
print("The flattened list:", result)


8. Nested List Average:

  Write a Python function that calculates the average of all elements in a nested list.

* Requirements:

  – Define a function average nested(lst) that takes a nested list lst and returns the average
  of all the elements.
  
  – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [24]:
def average_nested(lst):
    """
    Function to calculate the average of all elements in a nested list.
    """
    total = 0
    count = 0
    for item in lst:
        if isinstance(item, list):
            nested_total, nested_count = average_nested(item)
            total += nested_total
            count += nested_count
        else:
            total += item
            count += 1

    return total, count

total, count = average_nested([[1, 2], [3, 4], [5, 6]])
average = total / count if count > 0 else 0
print("The average of all the elements in the nested list is:",average)

The average of all the elements in the nested list is: 3.5


#**To - Do - NumPy**

#**10.1.Basic Vector and Matrix Operation with Numpy**

#Problem - 1: Array Creation:



In [25]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [26]:
empty_array = np.empty((2, 2), dtype=int)
print("The empty array:\n",empty_array)

The empty array:
 [[30442374        0]
 [       0       49]]


2. Initialize an all one array with size 4X2.

In [27]:
one_array = np.ones((4,2), dtype=int)
print("The array filled with ones:\n",one_array)

The array filled with ones:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}


In [28]:
array = np.full((3, 2), 8, dtype=int)
print("Array filled with 8:\n", array)

Array filled with 8:
 [[8 8]
 [8 8]
 [8 8]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [29]:
#The "array" was given above.
new_array = np.zeros_like(array)
print("The new array of zeros:\n", new_array)

The new array of zeros:
 [[0 0]
 [0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [30]:
#The "array" was given above.
new_array = np.ones_like(array)
print("The new array of zeros:\n", new_array)

The new array of zeros:
 [[1 1]
 [1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [31]:
new_list = [1, 2, 3, 4]
new_array = np.array(new_list)
print("The converted NumPy array:\n", new_array)
print("The type of array: ", type(new_array))

The converted NumPy array:
 [1 2 3 4]
The type of array:  <class 'numpy.ndarray'>


#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [32]:
array = np.arange(10, 50)
print("The array with values ranging from 10 to 49:\n", array)

The array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [33]:
matrix = np.arange(9).reshape(3, 3)
print("The 3x3 Matrix with values ranging from 0 to 8:\n", matrix)

The 3x3 Matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [34]:
matrix = np.eye(3, dtype=int)
print("The 3X3 identity matrix: \n", matrix)

The 3X3 identity matrix: 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [35]:
random_array = np.random.random(30)
mean_value = random_array.mean()

print("The random Array:\n", random_array)
print("\nThe mean of the array:", mean_value)

The random Array:
 [0.15602641 0.06756873 0.92394298 0.92398689 0.25501398 0.81205496
 0.88940331 0.06787881 0.53931643 0.99310092 0.87745041 0.3988853
 0.97789686 0.21053944 0.62459059 0.59230403 0.84413331 0.26813312
 0.82938255 0.5939052  0.55691388 0.14837204 0.9656445  0.12761033
 0.23964546 0.87342872 0.75643402 0.47686161 0.49854633 0.71334125]

The mean of the array: 0.5734104121237755


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [36]:
random_array = np.random.random((10, 10))
print(f"The 10*10 array with random values:\n{random_array}")

min_value = random_array.min()
max_value = random_array.max()
print(f"\nMinimum Values:{min_value}")
print(f"\nMaximum Values:{max_value}")


The 10*10 array with random values:
[[0.21119611 0.36514065 0.37208795 0.2808098  0.0571875  0.31212312
  0.11448686 0.53191141 0.27512098 0.7132498 ]
 [0.47651269 0.93565023 0.92780549 0.24084613 0.2581126  0.89118781
  0.43936634 0.69062094 0.9798998  0.78235915]
 [0.78540419 0.96003363 0.74499406 0.15145296 0.84672438 0.29164122
  0.85819943 0.60786615 0.14100398 0.63479189]
 [0.2915649  0.367526   0.15722357 0.52682414 0.88501184 0.16289421
  0.79956376 0.22306098 0.51950583 0.57411348]
 [0.58082973 0.11880756 0.51573869 0.35889449 0.11200965 0.86976385
  0.21961895 0.78337249 0.65652373 0.07588495]
 [0.78620611 0.50484936 0.06000004 0.751105   0.32484465 0.31268597
  0.82856803 0.1802886  0.02451012 0.03625696]
 [0.86219915 0.06712959 0.96687339 0.75948449 0.04328902 0.91050019
  0.74806302 0.83896232 0.27522441 0.36568437]
 [0.97479154 0.26561226 0.12944228 0.92908794 0.10477769 0.15947788
  0.28936259 0.71992485 0.84717527 0.04867307]
 [0.35656198 0.65927952 0.85376886 0.9680010

6. Create a zero array of size 10 and replace 5th element with 1.

In [37]:
zero_array = np.zeros(10, dtype=int)
zero_array[4] = 1
print("The zero array with 5th element replaced by 1:\n",zero_array)

The zero array with 5th element replaced by 1:
 [0 0 0 0 1 0 0 0 0 0]


7. Reverse an array arr = [1,2,0,0,4,0].

In [38]:
array = [1,2,0,0,4,0]
reversed_array = array[::-1]
print("The original array:",array)
print("The reversed array:",reversed_array)

The original array: [1, 2, 0, 0, 4, 0]
The reversed array: [0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [39]:
array = np.ones((5,5), dtype=int)
array[1:-1,1:-1] = 0
print("The 2d array with 1 on border and 0 inside:\n",array)

The 2d array with 1 on border and 0 inside:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [40]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Set 1s in odd rows, even columns
checkerboard[::2, 1::2] = 1  # Set 1s in even rows, odd columns
print("\nThe 8x8 Checkerboard Matrix:\n", checkerboard)


The 8x8 Checkerboard Matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

In [41]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

1. Add the two array.

In [42]:
print("Sum of 2D arrays x and y:")
add_xy = np.add(x, y)
print(add_xy)

print("\nSum of 1D arrays v and w:")
add_vw = np.add(v, w)
print(add_vw)

Sum of 2D arrays x and y:
[[ 6  8]
 [10 13]]

Sum of 1D arrays v and w:
[20 22]


2. Subtract the two array.

In [43]:
print("Subtraction of 2D arrays x and y:")
subtract_xy = np.subtract(x, y)
print(subtract_xy)

print("\nSubtraction of 1D arrays v and w:")
subtract_vw = np.subtract(v, w)
print(subtract_vw)

Subtraction of 2D arrays x and y:
[[-4 -4]
 [-4 -3]]

Subtraction of 1D arrays v and w:
[-2 -2]


3. Multiply the array with any integers of your choice.

In [44]:
print("Multiplication of 2D arrays (x): ")
multiply_x = np.dot(x,6)
print(multiply_x)

print("\nMultiplication of 1D arrays (v): ")
multiply_v = np.dot(v,6)
print(multiply_v)

Multiplication of 2D arrays (x): 
[[ 6 12]
 [18 30]]

Multiplication of 1D arrays (v): 
[54 60]


4. Find the square of each element of the array.

In [45]:
print("Square of 2D arrays (x):")
square_result = x ** 2
print(square_result)

print("\nSquare of 2D arrays (y):")
square_result = y ** 2
print(square_result)

print("\nSquare of 1D arrays (v):")
square_result = v ** 2
print(square_result)

print("\nSquare of 1D arrays (w):")
square_result = w ** 2
print(square_result)



Square of 2D arrays (x):
[[ 1  4]
 [ 9 25]]

Square of 2D arrays (y):
[[25 36]
 [49 64]]

Square of 1D arrays (v):
[ 81 100]

Square of 1D arrays (w):
[121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [46]:
dot_product_vw = np.dot(v, w)
print("Dot product of v and w:", dot_product_vw)
dot_product_xv = np.dot(x, v)
print("\nDot product of x and v:", dot_product_xv)
dot_product_xy = np.dot(x, y)
print("\nDot product of x and y:\n", dot_product_xy)

Dot product of v and w: 219

Dot product of x and v: [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [47]:
concat_rows = np.vstack((x, y))
print("Concatenation of x and y along rows:\n", concat_rows)

concat_columns = np.hstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_columns)

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [ 9 10 11 12]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [48]:
try:
    concat_error = np.concatenate((x, v))
except ValueError as e:
    print("\nError when concatenating x and v:")
    print(e)

# Fix the error by reshaping v into a 2D array
v_reshaped = v.reshape(1, -1)
concat_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\nConcatenation of x and reshaped v:\n", concat_fixed)


Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Concatenation of x and reshaped v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


# Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:


In [49]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

1. Prove A.A−1 = I.


In [50]:
A_inverse = np.linalg.inv(A)

# Multiply A by its inverse
result = np.dot(A, A_inverse)
print(f"A * A inverse:\n{np.round(result)}")

# Check if the result is the identity matrix
identity_matrix = np.eye(2)
print("\nIdentity Matrix:\n", identity_matrix)
print("\nIs A * A inverse equal to Identity Matrix?", np.allclose(result, identity_matrix))

A * A inverse:
[[1. 0.]
 [0. 1.]]

Identity Matrix:
 [[1. 0.]
 [0. 1.]]

Is A * A inverse equal to Identity Matrix? True


2. Prove AB ̸= BA.

In [51]:
dot_product_AB = np.dot(A, B)
dot_product_BA = np.dot(B, A)

# Compare AB and BA
print("AB:\n", dot_product_AB)
print("\nBA:\n", dot_product_BA)
print("\nIs AB equal to BA?", np.allclose(dot_product_AB, dot_product_BA))

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA? False


3. Prove (AB)^T = B^TA^T

In [52]:
AB_Trans = np.transpose(np.dot(A, B))
B_Trans_A_Trans = np.dot(np.transpose(B), np.transpose(A))

# Compare (AB)^T and B^T A^T
print("\n(AB)^T:\n", AB_Trans)
print("\nB^T A^T:\n", B_Trans_A_Trans)
print("\nIs (AB)^T equal to B^T A^T?", np.allclose(AB_Trans, B_Trans_A_Trans))


(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T? True


• Solve the following system of Linear equation using Inverse Methods.


  2x − 3y + z = −1

  x − y + 2z = −3
  
  3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [60]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])
print("Coefficient matrix A:")
print(A)
print("\nConstant matrix B:")
print(B)

Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant matrix B:
[-1 -3  9]


In [56]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

# Inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using X = A_inv * B
X = np.dot(A_inv, B)
print("Solution using Inverse Method:\n", X)

Solution using Inverse Method:
 [ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [57]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution using np.linalg.inv function:")
print(X)

Solution using np.linalg.inv function:
[ 2.  1. -2.]


#**10.2.Experiment: How Fast is Numpy?**

1. Element-wise Addition:

  • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
  and Print the time taken for this operation.

  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
  this operation.

In [61]:
import time

#Using Python List
list1 = list(range(1, 1000001))  # List from 1 to 1,000,000
list2 = list(range(1000000, 0, -1))  # List from 1,000,000 to 1

# Perform element-wise addition using a loop
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()

print("Time taken for Python Lists (Element-wise Addition): {:.6f} seconds".format(end_time - start_time))

#Using Numpy Arrays
array1 = np.arange(1, 1000001)  # Array from 1 to 1,000,000
array2 = np.arange(1000000, 0, -1)  # Array from 1,000,000 to 1

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("Time taken for NumPy Arrays (Element-wise Addition): {:.6f} seconds".format(end_time - start_time))

Time taken for Python Lists (Element-wise Addition): 0.095849 seconds
Time taken for NumPy Arrays (Element-wise Addition): 0.015827 seconds


2. Element-wise Multiplication:

  • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
  Measure and Print the time taken for this operation.

  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
  this operation.

In [62]:
import time

print("Element-wise Multiplication:\n")

# Using Python Lists
list1 = list(range(1, 1000001))
list2 = list(range(1000000, 0, -1))

start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()

print("Time taken for Python Lists (Element-wise Multiplication): {:.6f} seconds".format(end_time - start_time))

# Using NumPy Arrays
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("Time taken for NumPy Arrays (Element-wise Multiplication): {:.6f} seconds".format(end_time - start_time))

Element-wise Multiplication:

Time taken for Python Lists (Element-wise Multiplication): 0.131664 seconds
Time taken for NumPy Arrays (Element-wise Multiplication): 0.005484 seconds


3. Dot Product:

  • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
  Print the time taken for this operation.
  
  • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
  this operation.

In [63]:
import time

# Using Python Lists
list1 = list(range(1, 1000001))
list2 = list(range(1000000, 0, -1))

start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()

print("Time taken for Python Lists (Dot Product): {:.6f} seconds".format(end_time - start_time))

# Using NumPy Arrays
array1 = np.arange(1, 1000001)
array2 = np.arange(1000000, 0, -1)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

print("Time taken for NumPy Arrays (Dot Product): {:.6f} seconds".format(end_time - start_time))

Time taken for Python Lists (Dot Product): 0.083923 seconds
Time taken for NumPy Arrays (Dot Product): 0.001355 seconds


4. Matrix Multiplication:

  • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
  sure and print the time taken for this operation.

  • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
  Measure and print the time taken for this operation.

In [65]:
import time

size = 1000

# Using Python lists
matrix1_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]
matrix2_list = [[np.random.rand() for _ in range(size)] for _ in range(size)]

start_time = time.time()
result_list = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2_list)] for row in matrix1_list]
end_time = time.time()
python_time = end_time - start_time

print(f"Time taken using Python lists: {python_time:.4f} seconds")

# Using NumPy
matrix1_np = np.random.rand(size, size)
matrix2_np = np.random.rand(size, size)

start_time = time.time()
result_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
numpy_time = end_time - start_time

print(f"Time taken using NumPy: {numpy_time:.4f} seconds")


Time taken using Python lists: 84.9050 seconds
Time taken using NumPy: 0.0697 seconds
